import 'block_types.dart';

class BlockLibrary {
  static final List<CampaignBlock> blocks = [
    // --- HOOKS ---
    const CampaignBlock(
      id: 'hook_lagos_investor_fomo',
      type: CampaignBlockType.hook,
      template: '🔥 Only {units_remaining} units left in {neighborhood}, {city}! Secure your {property_type} at {price} before price increase.',
      applicableCities: ['lagos'],
      applicableAudiences: ['investor'],
      applicablePropertyTypes: ['all'],
      urgencyLevel: 'high',
    ),
    const CampaignBlock(
      id: 'hook_abuja_family_prestige',
      type: CampaignBlockType.hook,
      template: '🏡 Give your family the security and comfort they deserve in a premium gated {property_type} in {neighborhood}, {city}.',
      applicableCities: ['abuja'],
      applicableAudiences: ['family'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'hook_ph_investor_yield',
      type: CampaignBlockType.hook,
      template: '💰 Lock in high-yield returns with a premium {property_type} starting at {price} in the heart of {neighborhood}, {city}’s business corridor.',
      applicableCities: ['port_harcourt'],
      applicableAudiences: ['investor'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'hook_diaspora_trust',
      type: CampaignBlockType.hook,
      template: '🇳🇬 Dear Diaspora, build your wealth back home in {city} with verified properties starting at {price} and zero remote management stress.',
      applicableCities: ['all'],
      applicableAudiences: ['diaspora'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'hook_luxury_exclusive',
      type: CampaignBlockType.hook,
      template: '👑 Exclusive allocation: A masterfully designed {property_type} in {neighborhood}, {city} for {price} (discerning few only).',
      applicableCities: ['all'],
      applicableAudiences: ['luxury'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'hook_first_time_flexible',
      type: CampaignBlockType.hook,
      template: '🔑 Stop paying rent in {city}! Get your own {property_type} in {neighborhood} with an easy entry plan.',
      applicableCities: ['all'],
      applicableAudiences: ['first_time'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'hook_nigeria_default',
      type: CampaignBlockType.hook,
      template: '🏡 Outstanding {property_type} deal in {neighborhood}, {city} for {price}! Perfect opportunity for home ownership or rental income.',
      applicableCities: ['all'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),

    // --- VALUES ---
    const CampaignBlock(
      id: 'val_roi_appreciation',
      type: CampaignBlockType.value,
      template: '📈 Positioned in a rapid growth zone, this property offers projected capital appreciation and steady rental yield.',
      applicableCities: ['all'],
      applicableAudiences: ['investor'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'val_family_amenities',
      type: CampaignBlockType.value,
      template: '🌳 Features state-of-the-art security, 24/7 power, clean water, close proximity to top schools, and safe play areas.',
      applicableCities: ['all'],
      applicableAudiences: ['family'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'val_diaspora_process',
      type: CampaignBlockType.value,
      template: '🛡️ Comes with perfect title documentation, legal security, and structured progress reports sent directly to you.',
      applicableCities: ['all'],
      applicableAudiences: ['diaspora'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'val_luxury_finishes',
      type: CampaignBlockType.value,
      template: '💎 Built with premium imported finishes, smart home automation, custom layout, and double-volume spaces.',
      applicableCities: ['all'],
      applicableAudiences: ['luxury'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'val_first_time_payment',
      type: CampaignBlockType.value,
      template: '💳 Designed for affordability with structured payment plans and step-by-step guidance through the entire process.',
      applicableCities: ['all'],
      applicableAudiences: ['first_time'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'val_nigeria_default',
      type: CampaignBlockType.value,
      template: '✨ Features secure environment, clean water supply, access roads, and premium location advantages.',
      applicableCities: ['all'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),

    // --- PROOFS ---
    const CampaignBlock(
      id: 'proof_lagos_occupancy',
      type: CampaignBlockType.proof,
      template: '📊 Proof of value: Phase 1 is fully sold out, and Phase 2 is currently averaging 94% occupancy rate.',
      applicableCities: ['lagos'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'proof_abuja_gated',
      type: CampaignBlockType.proof,
      template: '🔒 Completed infrastructure with active gated security, paved roads, and satisfied families already residing.',
      applicableCities: ['abuja'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'proof_verified_title',
      type: CampaignBlockType.proof,
      template: '📑 Verified title check: Complete Governor’s Consent and registered Survey Certificate available for immediate search.',
      applicableCities: ['all'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'proof_investor_yield',
      type: CampaignBlockType.proof,
      template: '💰 Investors in Phase 1 have recorded over 35% capital growth in the last 12 months alone.',
      applicableCities: ['all'],
      applicableAudiences: ['investor'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'proof_diaspora_verified',
      type: CampaignBlockType.proof,
      template: '🛡️ Trusted by over 120 diaspora clients with remote verification and safe escrow payment routes.',
      applicableCities: ['all'],
      applicableAudiences: ['diaspora'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'proof_nigeria_default',
      type: CampaignBlockType.proof,
      template: '✅ Fully registered developer project with certified building approvals and milestone physical allocations.',
      applicableCities: ['all'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),

    // --- CTAS ---
    const CampaignBlock(
      id: 'cta_investor_urgency',
      type: CampaignBlockType.cta,
      template: '⚡ Act now! Contact us to lock in current launch prices before they increase by next month.',
      applicableCities: ['all'],
      applicableAudiences: ['investor'],
      applicablePropertyTypes: ['all'],
      urgencyLevel: 'high',
    ),
    const CampaignBlock(
      id: 'cta_family_visit',
      type: CampaignBlockType.cta,
      template: '📅 Book a safe weekend visit with your family to inspect this peaceful neighborhood first-hand.',
      applicableCities: ['all'],
      applicableAudiences: ['family'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'cta_diaspora_consultation',
      type: CampaignBlockType.cta,
      template: '📱 Send a message today to schedule a virtual tour and request detailed legal paperwork.',
      applicableCities: ['all'],
      applicableAudiences: ['diaspora'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'cta_luxury_private',
      type: CampaignBlockType.cta,
      template: '📞 Request a private, exclusive viewing and download the curated architectural brochure.',
      applicableCities: ['all'],
      applicableAudiences: ['luxury'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'cta_first_time_guide',
      type: CampaignBlockType.cta,
      template: '📩 Call or WhatsApp us to get our Beginner Homebuyer Guide and start with a flexible deposit.',
      applicableCities: ['all'],
      applicableAudiences: ['first_time'],
      applicablePropertyTypes: ['all'],
    ),
    const CampaignBlock(
      id: 'cta_nigeria_default',
      type: CampaignBlockType.cta,
      template: '📞 Call or WhatsApp us today to book an inspection and secure your unit.',
      applicableCities: ['all'],
      applicableAudiences: ['all'],
      applicablePropertyTypes: ['all'],
    ),
  ];
}
