name: CI/CD & Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_and_test:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Recreate env.txt
        run: |
          echo "$ENV_TXT" > env.txt
        env:
          ENV_TXT: ${{ secrets.ENV_TXT }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Lint & Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run unit tests
        run: flutter test

  deploy_web:
    name: Build & Deploy Web
    needs: [analyze_and_test, build_apk]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web release
        run: flutter build web --release

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: build/web

      - name: Rename APK in Web folder
        run: mv build/web/app-release.apk build/web/scalewealthestate-release.apk

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build_apk:
    name: Build Android APK
    needs: analyze_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
